
// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { lazy } from "react";
import { RouteObject } from "react-router-dom";


import { UserGuard } from "app";


import { StackHandlerRoutes, LoginRedirect } from "app/auth";


const App = lazy(() => import("./pages/App.tsx"));
const Companies = lazy(() => import("./pages/Companies.tsx"));
const Projects = lazy(() => import("./pages/Projects.tsx"));
const TimeTracking = lazy(() => import("./pages/TimeTracking.tsx"));

export const userRoutes: RouteObject[] = [

	{ path: "/auth/redirect", element: <LoginRedirect />},
	{ path: "/auth/*", element: <StackHandlerRoutes />},
	{ path: "/", element: <App />},
	{ path: "/companies", element: <UserGuard><Companies /></UserGuard>},
	{ path: "/projects", element: <UserGuard><Projects /></UserGuard>},
	{ path: "/time-tracking", element: <UserGuard><TimeTracking /></UserGuard>},
	{ path: "/timetracking", element: <UserGuard><TimeTracking /></UserGuard>},

];
